### ISSUE TITLE
Issu with copy action 

### ISSUE THREAD

**Issue by sarowarhosen03** [Abdullah-Mazumder/react-native-quran-app#2]
When I'm pres The copy button i got sura undefined . There was a data access issu i think 
Eg,
    بِسۡمِ اللّٰہِ الرَّحۡمٰنِ الرَّحِیۡمِ ﴿۱﴾ শুরু করছি আল্লাহর নামে যিনি পরম করুণাময়, অতি দয়ালু। In the name of Allah, the Entirely Merciful, the Especially Merciful. সূরা - undefined আয়াত - ১

**Comment by Abdullah-Mazumder** [comment]
actually, this is the older version. you can check this
https://drive.google.com/file/d/1OwdAd6UvjshgkpY9s8kxPAby8D9QO1XR/view?usp=sharing

**Comment by sarowarhosen03** [comment]
That's good thanks for updating it
